yunify/qingcloud-cloud-controller-manager

- Makefile
- pkg/eip/qingcloud_eip.go
when use auto mode and find no available eips, codes will return instead of allocate a new one
> 🚑  fix bug in auto mode

- pkg/executor/lb_executor.go
- pkg/loadbalance/loadbalancer.go
- test/pkg/e2e/e2e_test.go
- test/pkg/e2eutil/e2eutil.go
In auto mode, when users didn't specify the instance-id, and using in a service, lb will still fail with this service even after the instance-id is set properly
> 🚑 fix bug in auto mode

- hack/debug.sh
- pkg/eip/interface.go
- pkg/eip/qingcloud_eip.go
- pkg/executor/interface.go
- pkg/executor/lb.go
- pkg/executor/sg.go
- pkg/executor/tags.go
- pkg/qingcloud/loadbalancer_impl.go
- test/config/qingcloud.yaml
- test/pkg/fake/lb.go
- test/pkg/fake/security_group.go
> 🌟support add tags to resources

- README.md
> 📖 update docs

- CHANGELOG.md
- Makefile
- README.md
- deploy/kube-cloud-controller-manager.yaml
- pkg/loadbalance/loadbalancer.go
- pkg/qingcloud/qingcloud.go
/kind documentation
/kind design
> ✨release v1.4.0

- docs/configure.md
- pkg/loadbalance/annotations.go
- pkg/loadbalance/loadbalance_test.go
- pkg/loadbalance/loadbalancer.go
- test/test_cases/reuse/reuselb.yaml
fix #83
/kind feature
/kind documentation
> ✨support use user's lb

- docs/configure.md
- pkg/loadbalance/annotations.go
- pkg/loadbalance/loadbalancer.go
- pkg/loadbalance/loadbalancer_listener.go
- pkg/qingcloud/loadbalancer_impl.go
- test/test_cases/internal.yaml
> 🌟 support internal vxnet

- README.md
- deploy/kube-cloud-controller-manager.yaml
- pkg/loadbalance/loadbalancer.go
- pkg/qingcloud/loadbalancer_impl.go
- test/pkg/e2e/e2e_test.go
> 📖 update some docs

- docs/configure.md
- go.mod
- go.sum
- hack/debug.sh
- pkg/executor/lb.go
- pkg/loadbalance/annotations.go
- pkg/loadbalance/loadbalancer.go
- test/test_cases/internal.yaml
- vendor/k8s.io/klog/.travis.yml
- vendor/k8s.io/klog/OWNERS
- vendor/k8s.io/klog/README.md
- vendor/k8s.io/klog/SECURITY_CONTACTS
- vendor/k8s.io/klog/go.mod
- vendor/k8s.io/klog/go.sum
- vendor/k8s.io/klog/klog.go
- vendor/k8s.io/klog/klog_file.go
- vendor/modules.txt
> ✨ support internal ip

- pkg/loadbalance/annotations.go
- pkg/loadbalance/loadbalance_test.go
- pkg/loadbalance/loadbalancer.go
- pkg/loadbalance/loadbalancer_listener.go
- pkg/qingcloud/loadbalancer_impl.go
- test/pkg/e2e/e2e_test.go
- test/test_cases/reuse/reuselb-internal.yaml
> ✨support reuse-mode

- CHANGELOG.md
- Makefile
- deploy/kube-cloud-controller-manager.yaml
- docs/configure.md
> add docs about internal lb

- pkg/executor/tags.go
- pkg/loadbalance/annotations.go
- pkg/loadbalance/loadbalancer_listener.go
> Bugfix: don't detach tag when tags is empty

- README.md
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
> Optimized installation documentation

- README.md
should ensure that the cluster contains at least two nodes before installation
Signed-off-by: Duan Jiong <djduanjiong@gmail.com>
> Update install doc

- config/default/manager_image_patch.yaml
- deploy/kube-cloud-controller-manager.yaml
Signed-off-by: Zhengyi Lai <zheng1@yunify.com>
> Update image version to v1.4.6

- pkg/qingcloud/qingcloud.go
Signed-off-by: zhangziren zirenzhang@yunify.com
> Bugfix: use correct listenerID when UpdateLoadBalancer

- docs/configure.md
- pkg/apis/types.go
- pkg/executor/listener.go
- pkg/qingcloud/annotations.go
- pkg/qingcloud/loadbalancer_test.go
- pkg/qingcloud/loadbalancer_utils.go
- pkg/qingcloud/qingcloud.go
Signed-off-by: jacksontong <jacksontong@yunify.com>
> Support lb's listener configuration

- docs/configure.md
- pkg/controllers/endpoint/endpoint_controller.go
- pkg/executor/client.go
- pkg/executor/lb.go
- pkg/qingcloud/annotations.go
- pkg/qingcloud/qingcloud.go
- pkg/qingcloud/qingcloud_utils.go
Signed-off-by: gangqiangwang <gangqiangwang@yunify.com>;
> support change loadbalancer eip;

- docs/configure.md
- pkg/qingcloud/annotations.go
- pkg/qingcloud/loadbalancer_test.go
- pkg/qingcloud/loadbalancer_utils.go
- pkg/qingcloud/qingcloud.go
- pkg/qingcloud/qingcloud_utils.go
- pkg/util/util.go
Signed-off-by: gangqiangwang <gangqiangwang@yunify.com>;
> support config lb backend nodes count for service;

- docs/configure.md
- pkg/apis/types.go
- pkg/controllers/clusternode/cluster_node_controller.go
- pkg/controllers/endpoint/endpoint_controller.go
- pkg/errors/errors.go
- pkg/executor/backend.go
- pkg/executor/lb.go
- pkg/executor/listener.go
- pkg/executor/sg.go
- pkg/qingcloud/annotation_valid.go
- pkg/qingcloud/annotations.go
- pkg/qingcloud/loadbalancer_utils.go
Signed-off-by: gangqiangwang <gangqiangwang@yunify.com>;
> support config lb listener timeout;

- Makefile
- deploy/DockerFileWithBuilder
- deploy/kube-cloud-controller-manager.yaml
- docs/configure.md
- pkg/controllers/service/cloud_service_controller.go
- pkg/executor/sg.go
- pkg/qingcloud/annotations.go
- pkg/qingcloud/loadbalancer_utils.go
- pkg/qingcloud/qingcloud.go
- pkg/qingcloud/qingcloud_utils.go
keep auto created lb when there are some other listeners; append eip to lb as default, add an annotation to config lb eip change strategy; fix ensure sg panic;
update ccm deploy to v1.4.18;
Signed-off-by: gangqiangwang <gangqiangwang@yunify.com>;
> update delete lb, update change eip;
